version: "3"
services:
  app:
    build: .
    image: mew13/flappy-chat
    ports:
      - "5050:8080"
    environment:
      - REACT_APP_PUBLIC_URL=http://localhost:5050
      - REACT_APP_ROLLBAR_ACCESS_TOKEN=none
      - WDS_SOCKET_PORT=5050
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - ./frontend/.env.development:/app/frontend/.env.development
      - ./frontend/.eslintrc.yml:/app/frontend/.eslintrc.yml
      - ./frontend/.eslintignore:/app/frontend/.eslintignore
      - ./frontend/.prettierrc:/app/frontend/.prettierrc
      - ./frontend/.prettierignore:/app/frontend/.prettierignore
      - ./frontend/craco.config.js:/app/frontend/craco.config.js